// Bundled demo data so the app runs standalone (e.g. on GitHub Pages)
// with no backend required. Mirrors the seed data in backend/app/seed.py.
export const MOCK_CONTROLS = [
  { id: 1, name: "Single sign-on (SSO)", description: "All production systems require SSO via the corporate identity provider; no standalone credentials.", category: "security", status: "verified", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-08-01T00:00:00Z" },
  { id: 2, name: "Static application security testing (SAST)", description: "Every pull request is scanned for known vulnerability patterns before merge.", category: "security", status: "verified", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-08-01T00:00:00Z" },
  { id: 3, name: "Dependency scanning", description: "Automated scanning of third-party dependencies for known CVEs on every build.", category: "security", status: "implemented", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-07-20T00:00:00Z" },
  { id: 4, name: "Vulnerability remediation SLA", description: "Critical vulnerabilities are remediated within 7 days, high within 30 days.", category: "security", status: "implemented", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-07-20T00:00:00Z" },
  { id: 5, name: "Access review (quarterly)", description: "Quarterly review of who has access to production systems and data stores.", category: "security", status: "in_progress", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-06-15T00:00:00Z" },
  { id: 6, name: "Encryption at rest", description: "All production databases and object storage are encrypted at rest.", category: "confidentiality", status: "verified", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-08-01T00:00:00Z" },
  { id: 7, name: "Encryption in transit", description: "TLS 1.2+ enforced for all external and internal service-to-service traffic.", category: "confidentiality", status: "verified", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-08-01T00:00:00Z" },
  { id: 8, name: "Backup restoration testing", description: "Quarterly test restore of production backups to verify recoverability.", category: "availability", status: "in_progress", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-06-01T00:00:00Z" },
  { id: 9, name: "Incident response plan", description: "Documented incident response runbook with defined escalation paths.", category: "availability", status: "implemented", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-07-10T00:00:00Z" },
  { id: 10, name: "Change management", description: "All production changes go through code review and a documented deploy process.", category: "processing_integrity", status: "verified", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-08-01T00:00:00Z" },
  { id: 11, name: "Centralized logging & monitoring", description: "Application and infrastructure logs are centralized with alerting on anomalies.", category: "availability", status: "implemented", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-07-15T00:00:00Z" },
  { id: 12, name: "Vendor risk management", description: "Third-party vendors handling customer data are reviewed before onboarding.", category: "security", status: "not_started", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-05-01T00:00:00Z" },
  { id: 13, name: "Security awareness training", description: "Annual security awareness training completed by all engineering staff.", category: "security", status: "not_started", owner: "Jaskaran Singh", evidence_url: "", last_reviewed: "2026-05-01T00:00:00Z" },
];
